knpu_oauth2_client:
    clients:
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
        # will create service: "knpu.oauth2.client.github"
        # an instance of: KnpU\OAuth2ClientBundle\Client\Provider\GithubClient
        # composer require league/oauth2-github
        openstreetmap:
            type: generic
            provider_class: JBelien\OAuth2\Client\Provider\OpenStreetMap
            # add and set these environment variables in your .env files
            client_id: '%env(OAUTH_OSM_CLIENT_ID)%'
            client_secret: '%env(OAUTH_OSM_CLIENT_SECRET)%'
            # a route name you'll create
            redirect_route: connect_openstreetmap_check
            redirect_params: {}
            # optional: if your provider has custom constructor options
            # provider_options: {}
            # whether to check OAuth2 "state": defaults to true
            # use_state: true
