regions:
  belgium:
    name: Belgium
    locales: fr|nl|de
    osmcha.id: 640be7af-1f93-4d9c-a521-66cfdd59e6b8
  italy:
    name: Italy
    locales: it
    osmcha.id: a599d3cb-dac6-4190-be98-580c14888e38
