regions:
  belgium:
    name: Belgium
    locales: fr|nl|de
    osmcha.id: d36d8b8d-d78e-452c-a36c-3a13a903360e
  italy:
    name: Italy
    locales: it
    osmcha.id: a599d3cb-dac6-4190-be98-580c14888e38
