regions:
  belgium:
    name: Belgium
    locales: fr|nl|de
    osmcha.id: 640be7af-1f93-4d9c-a521-66cfdd59e6b8
  italy:
    name: Italy
    locales: it
    osmcha.id: ac2598cc-9b66-432e-b195-9b93e21c5d26
