name: PHP

on:
  push:
    branches: [ 2.x ]
  pull_request:
    branches: [ 2.x ]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run Composer check
      run: vendor/bin/grumphp run --testsuite=composer

    - name: Run checks
      run: vendor/bin/grumphp run --testsuite=check

    # - name: Run test suite
    #   run: vendor/bin/phpunit
